// src/components/home/home.component.ts
import { Component, inject, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';
import { ContentService, Post } from '../../services/content.service';
import { NgOptimizedImage } from '@angular/common';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: [],
  imports: [CommonModule, RouterLink, NgOptimizedImage],
})
export class HomeComponent {
  private contentService = inject(ContentService);
  latestPosts = this.contentService.latestPosts;

  // Expose site settings for dynamic font application in template
  siteSettings = this.contentService.siteSettings;
  headerFont = computed(() => this.siteSettings().headerFont);
  bodyFont = computed(() => this.siteSettings().bodyFont);

  impactStats = [
    { value: '৫০০+', label: 'ছাত্র-ছাত্রীকে সাহায্য করা হয়েছে' },
    { value: '২৫+', label: 'স্বাস্থ্য শিবির আয়োজিত' },
    { value: '২০০০+', label: 'বৃক্ষ রোপণ করা হয়েছে' },
    { value: '৭+', label: 'বছর ধরে সেবা' }
  ];
}
<div class="font-sans">
  <!-- Hero Section -->
  <section class="relative bg-cover bg-center h-[60vh] flex items-center justify-center text-center p-4"
           [style.background-image]="'url(src/assets/images/chatrodol.jpg)'">
           

    <div class="absolute inset-0 bg-black opacity-60"></div>
    <div class="relative z-10 text-white max-w-4xl mx-auto">
      <h1 class="text-4xl md:text-6xl font-extrabold mb-4" [style.fontFamily]="headerFont()">
        নাড়াজোল ছাত্রদল: একতা, শিক্ষা, উন্নতি
      </h1>
      <p class="text-lg md:text-xl mb-8" [style.fontFamily]="bodyFont()">
        আমরা নাড়াজোলের প্রতিটি মানুষের জন্য একটি উজ্জ্বল ও সমৃদ্ধ ভবিষ্যৎ গড়তে প্রতিশ্রুতিবদ্ধ।
      </p>
      <div class="flex flex-col sm:flex-row justify-center space-y-4 sm:space-y-0 sm:space-x-4">
        <a routerLink="/donate" class="inline-block bg-blue-600 hover:bg-blue-700 text-white font-bold py-3 px-8 rounded-full shadow-lg transition duration-300 ease-in-out" [style.fontFamily]="bodyFont()">
          অনুদান দিন
        </a>
        <a routerLink="/volunteer" class="inline-block bg-green-500 hover:bg-green-600 text-white font-bold py-3 px-8 rounded-full shadow-lg transition duration-300 ease-in-out" [style.fontFamily]="bodyFont()">
          আমাদের সাথে যোগ দিন
        </a>
      </div>
    </div>
  </section>

  <!-- Impact Summary Section -->
  <section class="py-16 bg-gray-100">
    <div class="container mx-auto px-4 md:px-8 text-center">
      <h2 class="text-3xl md:text-4xl font-bold text-gray-800 mb-10" [style.fontFamily]="headerFont()">
        আমাদের কার্যক্রমের প্রভাব
      </h2>
      <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-8">
        @for (stat of impactStats; track stat.label) {
          <div class="bg-white p-6 rounded-lg shadow-md flex flex-col items-center">
            <div class="text-blue-600 text-5xl font-extrabold mb-2" [style.fontFamily]="headerFont()">{{ stat.value }}</div>
            <p class="text-xl font-semibold text-gray-700 text-center" [style.fontFamily]="bodyFont()">{{ stat.label }}</p>
          </div>
        }
      </div>
    </div>
  </section>

  <!-- Latest News/Events Feed -->
  <section class="py-16">
    <div class="container mx-auto px-4 md:px-8">
      <h2 class="text-3xl md:text-4xl font-bold text-gray-800 mb-10 text-center" [style.fontFamily]="headerFont()">
        সর্বশেষ খবর ও অনুষ্ঠান
      </h2>
      @if (latestPosts().length > 0) {
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          @for (post of latestPosts(); track post.id) {
            <div class="bg-white rounded-lg shadow-md overflow-hidden transform hover:scale-105 transition-transform duration-300">
              <img [ngSrc]="post.featuredImage" [alt]="post.title" width="800" height="600" class="w-full h-56 object-cover">
              <div class="p-6">
                <h3 class="text-xl font-semibold text-gray-900 mb-2" [style.fontFamily]="headerFont()">{{ post.title }}</h3>
                <p class="text-sm text-blue-600 mb-3" [style.fontFamily]="bodyFont()">{{ post.category }} | {{ post.publishedDate | date:'mediumDate' }}</p>
                <p class="text-gray-700 text-base mb-4 line-clamp-3" [style.fontFamily]="bodyFont()">{{ post.content }}</p>
                <!-- <a href="#" class="inline-flex items-center text-blue-600 hover:text-blue-800 font-medium" [style.fontFamily]="bodyFont()">
                  বিস্তারিত দেখুন
                  <svg class="ml-1 w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 8l4 4m0 0l-4 4m4-4H3"></path></svg>
                </a> -->
              </div>
            </div>
          }
        </div>
        <div class="text-center mt-10">
          <a routerLink="/events" class="inline-block bg-green-500 hover:bg-green-600 text-white font-bold py-3 px-8 rounded-full shadow-lg transition duration-300 ease-in-out" [style.fontFamily]="bodyFont()">
            সকল খবর ও ইভেন্ট দেখুন
          </a>
        </div>
      } @else {
        <p class="text-center text-gray-600 text-lg" [style.fontFamily]="bodyFont()">কোন পোস্ট পাওয়া যায়নি।</p>
      }
    </div>
  </section>
</div>

// src/pages/Home.tsx
import { Link } from 'react-router-dom';
import { IMPACT_STATS, ORG } from '@/data/content';
import { usePosts } from '@/hooks/usePosts';
import PostCard from '@/components/PostCard';

export default function Home() {
  const { posts } = usePosts();
  const latest = posts.slice(0, 3);

  return (
    <div>
      {/* Hero */}
      <section
        className="relative flex h-[60vh] min-h-[420px] items-center justify-center bg-cover bg-center p-4 text-center"
        style={{ backgroundImage: 'url(/assets/images/chatrodol.jpg)' }}
      >
        <div className="absolute inset-0 bg-black/60" />
        <div className="relative z-10 mx-auto max-w-4xl text-white">
          <h1 className="mb-4 text-4xl font-extrabold md:text-6xl">
            {ORG.nameBn}: {ORG.taglineBn}
          </h1>
          <p className="mb-8 text-lg md:text-xl">
            আমরা নাড়াজোলের প্রতিটি মানুষের জন্য একটি উজ্জ্বল ও সমৃদ্ধ ভবিষ্যৎ গড়তে প্রতিশ্রুতিবদ্ধ।
          </p>
          <div className="flex flex-col justify-center gap-4 sm:flex-row">
            <Link
              to="/donate"
              className="rounded-full bg-blue-600 px-8 py-3 font-bold text-white shadow-lg transition hover:bg-blue-700"
            >
              অনুদান দিন
            </Link>
            <Link
              to="/volunteer"
              className="rounded-full bg-green-500 px-8 py-3 font-bold text-white shadow-lg transition hover:bg-green-600"
            >
              আমাদের সাথে যোগ দিন
            </Link>
          </div>
        </div>
      </section>

      {/* Impact stats */}
      <section className="bg-gray-100 py-16">
        <div className="container mx-auto px-4 text-center md:px-8">
          <h2 className="mb-10 text-3xl font-bold text-gray-800 md:text-4xl">আমাদের কার্যক্রমের প্রভাব</h2>
          <div className="grid grid-cols-1 gap-8 sm:grid-cols-2 lg:grid-cols-4">
            {IMPACT_STATS.map((stat) => (
              <div key={stat.label} className="flex flex-col items-center rounded-lg bg-white p-6 shadow-md">
                <div className="mb-2 text-5xl font-extrabold text-blue-600">{stat.value}</div>
                <p className="text-lg font-semibold text-gray-700">{stat.label}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Latest */}
      <section className="py-16">
        <div className="container mx-auto px-4 md:px-8">
          <h2 className="mb-10 text-center text-3xl font-bold text-gray-800 md:text-4xl">
            সর্বশেষ খবর ও অনুষ্ঠান
          </h2>
          <div className="grid grid-cols-1 gap-8 md:grid-cols-2 lg:grid-cols-3">
            {latest.map((post) => (
              <PostCard key={post.id} post={post} />
            ))}
          </div>
          <div className="mt-10 text-center">
            <Link
              to="/events"
              className="inline-block rounded-full bg-green-500 px-8 py-3 font-bold text-white shadow-lg transition hover:bg-green-600"
            >
              সকল খবর ও ইভেন্ট দেখুন
            </Link>
          </div>
        </div>
      </section>
    </div>
  );
}
